database:
  driver: "postgres"
  dbname: "go-commerce"
  username: "postgres"
  password: "postgres"
  host: "localhost"
  port: "5432"
  logmode: true

rabbitmq:
  connection: "amqp://guest:guest@localhost:49154/"
  mailVerifiedQueue: "mail-verified-queue"

redis:
  connection: "redis://default:redispw@localhost:49153"

server:
  host: "localhost"
  port: "3333"
  accessTokenSecret: "mySecretKey"
  refreshTokenSecret: "mySecretKey"
  accessTokenExpireDuration: 1
  refreshTokenExpireDuration: 720
  limitCountPerRequest: 1
