version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      driver: "postgres"
      dbname: "go-commerce"
      username: "postgres"
      password: "postgres"
      host: "localhost"
      port: "5432"
      logmode: true
  redis:
    image: redis
    ports:
      - "6379:6379"
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DATABASE_URL=db
      - REDIS_URL=redis
    depends_on:
      - db
      - redis
